package com.github.pmoerenhout.atcommander;

public enum RejectCause {
  NO_ERROR(0, "NO ERROR"),
  IMSI_UNKNOWN_IN_HLR(2, "IMSI UNKNOWN IN HLR"),
  ILLEGAL_MS(3, "ILLEGAL MS"),
  IMSI_UNKNOWN_IN_VISITOR_LR(4, "IMSI UNKNOWN IN VISITOR LR"),
  IMEI_NOT_ACCEPTED(5, "IMEI NOT ACCEPTED"),
  ILLEGAL_ME(6, "ILLEGAL ME"),
  GPRS_NOT_ALLOWED(7, "GPRS NOT ALLOWED"),
  GPRS_AND_NON_GPRS_NOT_ALLOWED(8, "GPRS AND NON GPRS NOT ALLOWED"),
  MS_IDENTITY_CANNOT_BE_DERIVED_BY_NETWORK(9, "MS IDENTITY CANNOT BE DERIVED BY NETWORK"),
  IMPLICITLY_DETACHED(10, "IMPLICITLY DETACHED"),
  PLMN_NOT_ALLOWED(11, "PLMN NOT ALLOWED"),
  LA_NOT_ALLOWED(12, "LA NOT ALLOWED"),
  ROAMING_NOT_ALLOWED(13, "ROAMING NOT ALLOWED"),
  GPRS_NOT_ALLOWED_IN_THIS_PLMN(14, "GPRS NOT ALLOWED IN THIS PLMN"),
  NO_SUITABLE_CELLS_IN_LA(15, "NO SUITABLE CELLS IN LA"),
  MSC_TEMP_NOT_REACHABLE(16, "MSC TEMP NOT REACHABLE"),
  NETWORK_FAILURE(17, "NETWORK FAILURE"),
  CONGESTION(22, "CONGESTION"),
  LLC_OR_SNDCP_FAILURE(25, "LLC OR SNDCP FAILURE"),
  INSUFFICIENT_RESOURCES(26, "INSUFFICIENT RESOURCES"),
  MISSING_OR_UNKNOWN_APN(27, "MISSING OR UNKNOWN APN"),
  UNKNOWN_PDP_ADDRESS_OR_PDP_TYPE(28, "UNKNOWN PDP ADDRESS OR PDP TYPE"),
  USER_AUTHENTICATION_FAILED(29, "USER AUTHENTICATION FAILED"),
  ACTIVATION_REJECTED_BY_GGSN(30, "ACTIVATION REJECTED BY GGSN"),
  ACTIVATION_REJECTED_UNSPECIFIED(31, "ACTIVATION REJECTED UNSPECIFIED"),
  SERVICE_OPTION_NOT_SUPPORTED(32, "SERVICE OPTION NOT SUPPORTED"),
  REQ_SERVICE_OPTION_NOT_SUBSCRIBED(33, "REQUESTED SERVICE OPTION NOT SUBSCRIBED"),
  SERVICE_OPTION_TEMPORARILY_OUT_OF_ORDER(34, "SERVICE OPTION TEMPORARILY OUT OF ORDER"),
  NSAPI_ALREADY_USED(35, "NSAPI ALREADY USED"),
  REGULAR_DEACTIVATION(36, "REGULAR DEACTIVATION"),
  QOS_NOT_ACCEPTED(37, "QOS NOT ACCEPTED"),
  SMN_NETWORK_FAILURE(38, "SMN NETWORK FAILURE"),
  REACTIVATION_REQUIRED(39, "REACTIVATION REQUIRED"),
  FEATURE_NOT_SUPPORTED(40, "FEATURE NOT SUPPORTED"),
  CONDITINAL_IE_ERROR(100, "CONDITIONAL IE ERROR"),
  PROTOCOL_ERROR_UNSPECIFIED(111, "PROTOCOL ERROR UNSPECIFIED"),
  APN_RESTRICT_VALUE_INCOMPATIBLE_WITHOUT_PDP_CONTEXT(112, "APN RESTRICT VALUE INCOMPATIBLE WITHOUT PDP CONTEXT"),
  //http://www.arib.or.jp/english/html/overview/doc/STD-T63V12_00/5_Appendix/Rel13/24/24302-d50.pdf
  MULTIPLE_ACCESSES_TO_A_PDN_CONNECTION_NOT_ALLOWED(113, "MULTIPLE ACCESSES TO A PDN CONNECTION NOT ALLOWED");

  private final int value;
  private final String diagnostic;

  RejectCause(int value, String diagnostic) {
    this.value = value;
    this.diagnostic = diagnostic;
  }

  public static RejectCause fromInt(final int rejectCause) {
    for (final RejectCause s : RejectCause.values()) {
      if (s.value() == rejectCause) {
        return s;
      }
    }
    return null;
  }

  public int value() {
    return value;
  }

  public String diagnostic() {
    return diagnostic;
  }
}
